[package]
name = "pallas-alonzo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minicbor = "0.11.5"
minicbor-derive = "0.7.2"
hex = "0.4.3"
minicbor-io = "0.6.0"
log = "0.4.14"
