[package]
name = "pallas-multiplexer"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/txpipe/pallas"
license = "Apache-2.0"
authors = [
    "Santiago Carmuega <santiago@carmuega.me>"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
byteorder = "1.4.3"
hex = "0.4.3"

[dev-dependencies]
env_logger = "0.9.0"
